version: 0.2

env: 
  variables: 
    IMAGE_NAME: awscli-test
    IMAGE_TAG: latest
    CONTAINER_NAME: awscli-container

phases: 
  pre_build: 
    commands:
      - IMAGE_NAME=awscli-test
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 442005027450.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - echo $AWS_SESSION_TOKEN
      - docker build -t $IMAGE_NAME .
  build:
    commands:
      - IMAGE_NAME=awscli-test
      # The following command works:
      # - docker run -d --name $CONTAINER_NAME -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI $IMAGE_NAME aws s3 ls && aws sts get-caller-identity
      # Testing Cx's command
      - echo $CONTAINER_NAME
      - docker run -d --name $CONTAINER_NAME $IMAGE_NAME
      - docker ps
      - docker exec -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI ${CONTAINER_NAME} /bin/bash -c "aws --version && aws sts get-caller-identity"
      
artifacts:
  files:
    - "**/*"
