version: 0.2

env: 
  variables: 
    IMAGE_NAME: awscli-test
    IMAGE_TAG: latest

phases: 
  pre_build: 
    commands:
      - IMAGE_NAME=awscli-test
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 442005027450.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - echo $AWS_SESSION_TOKEN
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  build:
    commands:
      - IMAGE_NAME=awscli-test
      - docker run -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI $IMAGE_TAG aws s3 ls
      # - docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION $IMAGE_NAME aws s3 ls

artifacts:
  files:
    - "**/*"
